In [1]:
import pandas as pd
import requests

In [3]:
import requests

url = "https://api.themoviedb.org/3/genre/movie/list?language=en"

headers = {
    "accept": "application/json",
    "Authorization": "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI0YWUxZjFkZTIxM2MyMTZjMTFlOWI1MGVmYjgxYjAwNCIsIm5iZiI6MTc1MDcwMDk4MC41MjQsInN1YiI6IjY4NTk5M2I0OWY3ZTZkMzQ2ZTc5Njk1ZSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.wTJ9I_7Ye1p5b4BkUCdHFhOYwC4Mf_s8Y8mELXkVaMg"
}

response = requests.get(url, headers=headers)

print(response.text)

{"genres":[{"id":28,"name":"Action"},{"id":12,"name":"Adventure"},{"id":16,"name":"Animation"},{"id":35,"name":"Comedy"},{"id":80,"name":"Crime"},{"id":99,"name":"Documentary"},{"id":18,"name":"Drama"},{"id":10751,"name":"Family"},{"id":14,"name":"Fantasy"},{"id":36,"name":"History"},{"id":27,"name":"Horror"},{"id":10402,"name":"Music"},{"id":9648,"name":"Mystery"},{"id":10749,"name":"Romance"},{"id":878,"name":"Science Fiction"},{"id":10770,"name":"TV Movie"},{"id":53,"name":"Thriller"},{"id":10752,"name":"War"},{"id":37,"name":"Western"}]}

In [5]:
pd.DataFrame(response.json()['genres'])

       id             name
0      28           Action
1      12        Adventure
2      16        Animation
3      35           Comedy
4      80            Crime
5      99      Documentary
6      18            Drama
7   10751           Family
8      14          Fantasy
9      36          History
10     27           Horror
11  10402            Music
12   9648          Mystery
13  10749          Romance
14    878  Science Fiction
15  10770         TV Movie
16     53         Thriller
17  10752              War
18     37          Western

In [7]:
import requests

url = "https://api.themoviedb.org/3/discover/tv?include_adult=false&include_null_first_air_dates=false&language=en-US&page=1&sort_by=popularity.desc"

headers = {
    "accept": "application/json",
    "Authorization": "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI0YWUxZjFkZTIxM2MyMTZjMTFlOWI1MGVmYjgxYjAwNCIsIm5iZiI6MTc1MDcwMDk4MC41MjQsInN1YiI6IjY4NTk5M2I0OWY3ZTZkMzQ2ZTc5Njk1ZSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.wTJ9I_7Ye1p5b4BkUCdHFhOYwC4Mf_s8Y8mELXkVaMg"
}

response = requests.get(url, headers=headers)

print(response.text)

{"page":1,"results":[{"adult":false,"backdrop_path":"/hHMWfDlqKisD5zVcZfz3KEw5U3v.jpg","genre_ids":[18,10751],"id":50821,"origin_country":["HU"],"original_language":"hu","original_name":"Barátok közt","overview":"Miklós introduces viewers into the world of Money and Charm.","popularity":675.433,"poster_path":"/kBBbSgNchtMvsgD6z1oI1RRluHP.jpg","first_air_date":"1998-10-26","name":"Among Friends","vote_average":3.2,"vote_count":14},{"adult":false,"backdrop_path":"/qLMfcvdCcCGD2BNLH8b6ZCBuO7D.jpg","genre_ids":[10763,35],"id":2224,"origin_country":["US"],"original_language":"en","original_name":"The Daily Show","overview":"The World's Fakest News Team tackle the biggest stories in news, politics and pop culture.","popularity":763.3525,"poster_path":"/ixcfyK7it6FjRM36Te4OdblAq4X.jpg","first_air_date":"1996-07-22","name":"The Daily Show","vote_average":6.363,"vote_count":578},{"adult":false,"backdrop_path":"/m0bV3qBiJBBlpFaaKjwHo13MVjm.jpg","genre_ids":[35,10767],"id":14981,"origin_country":["US"],"original_language":"en","original_name":"The Late Late Show with Craig Ferguson","overview":"The Late Late Show with Craig Ferguson is an American late-night talk show hosted by Scottish American comedian Craig Ferguson, who is the third regular host of the Late Late Show franchise. It follows Late Show with David Letterman in the CBS late-night lineup, airing weekdays in the US at 12:37 a.m. It is taped in front of a live studio audience from Monday to Friday at CBS Television City in Los Angeles, California, directly above the Bob Barker Studio. It is produced by David Letterman's production company Worldwide Pants Incorporated and CBS Television Studios.\n\nSince becoming host on January 3, 2005, after Craig Kilborn and Tom Snyder, Ferguson has achieved the highest ratings since the show's inception in 1995. While the majority of the episodes focus on comedy, Ferguson has also addressed difficult subject matter, such as the deaths of his parents, and undertaken serious interviews, such as one with Desmond Tutu, which earned the show a 2009 Peabody Award.","popularity":770.8415,"poster_path":"/gGC7zSDgG0FY0MbM1pjfhTCWQBI.jpg","first_air_date":"2005-01-03","name":"The Late Late Show with Craig Ferguson","vote_average":6.785,"vote_count":107},{"adult":false,"backdrop_path":"/kA50bkSC6bw5ZkutYrN9sLD9CZ9.jpg","genre_ids":[10767,35],"id":22980,"origin_country":["US"],"original_language":"en","original_name":"Watch What Happens Live with Andy Cohen","overview":"Bravo network executive Andy Cohen discusses pop culture topics with celebrities and reality show personalities.","popularity":560.8859,"poster_path":"/onSD9UXfJwrMXWhq7UY7hGF2S1h.jpg","first_air_date":"2009-07-16","name":"Watch What Happens Live with Andy Cohen","vote_average":5.136,"vote_count":77},{"adult":false,"backdrop_path":"/kkfqNkGQR5og5sDjJTxTVmI9PW.jpg","genre_ids":[80,18,10766],"id":72879,"origin_country":["FR"],"original_language":"fr","original_name":"Demain nous appartient","overview":"The story revolves around the people of Sète, France. Their lives are punctuated by family rivalries, romance and scenes from daily life, but also by plots involving police investigations, secrets and betrayals.","popularity":552.992,"poster_path":"/zMWldNZF0wS3L5XkDVFHxYhclcL.jpg","first_air_date":"2017-07-17","name":"Tomorrow Is Ours","vote_average":6.343,"vote_count":67},{"adult":false,"backdrop_path":"/Ajku4m7jbMpCTEPr794Imv19mCA.jpg","genre_ids":[10763,35],"id":4385,"origin_country":["US"],"original_language":"en","original_name":"The Colbert Report","overview":"The Colbert Report is an American satirical late night television program. It stars political humorist Stephen Colbert, a former correspondent for The Daily Show with Jon Stewart. The Colbert Report is a spin-off from and counterpart to The Daily Show that comments on politics and the media in a similar way. The show focuses on a fictional anchorman character named Stephen Colbert, played by his real-life namesake. The character, described by Colbert as a \"well-intentioned, poorly informed, high-status idiot\", is a caricature of televised political pundits.","popularity":534.6319,"poster_path":"/pn2CVXjOlR8kY5MgOTJjZ71IM0Q.jpg","first_air_date":"2005-10-17","name":"The Colbert Report","vote_average":6.862,"vote_count":276},{"adult":false,"backdrop_path":"/hvFCS0dMeC3ffiF4uYTKzUAkvYL.jpg","genre_ids":[35],"id":65701,"origin_country":["US"],"original_language":"en","original_name":"Good Mythical Morning","overview":"Two \"Internetainers\" (Rhett & Link) go far out and do the weirdest things, giving you a daily dose of casual comedy every Monday-Friday.","popularity":440.6367,"poster_path":"/jMpBQr2aNOFAI6wsC47zsOG6qOh.jpg","first_air_date":"2012-01-09","name":"Good Mythical Morning","vote_average":7.038,"vote_count":80},{"adult":false,"backdrop_path":"/92cc2hINaW72HTA0RqQaqPUbl4g.jpg","genre_ids":[16,35,10767],"id":46825,"origin_country":["US"],"original_language":"en","original_name":"Rooster Teeth Animated Adventures","overview":"The animated shenanigans of the Rooster Teeth staff. Audio taken from the Rooster Teeth Podcast.","popularity":407.691,"poster_path":"/xrcOsjmuBcmf1YhqyQ6qrGCcsvE.jpg","first_air_date":"2011-09-28","name":"Rooster Teeth Animated Adventures","vote_average":8.6,"vote_count":5},{"adult":false,"backdrop_path":"/7jEnft2CLNbILWAiBRIBrXNN7Qh.jpg","genre_ids":[10767,35],"id":498,"origin_country":["US"],"original_language":"en","original_name":"Late Show with David Letterman","overview":"Late Show with David Letterman is an American late-night talk show hosted by David Letterman on CBS. The show debuted on August 30, 1993, and is produced by Letterman's production company, Worldwide Pants Incorporated and CBS Television Studios. The show's music director and band-leader of the house band, the CBS Orchestra, is Paul Shaffer. The head writer is Matt Roberts and the announcer is Alan Kalter. Of the major U.S. late-night programs, Late Show ranks second in cumulative average viewers over time and third in number of episodes over time. The show leads other late night shows in ad revenue with $271 million in 2009.\n\nIn most U.S. markets the show airs at 11:35 p.m. Eastern/Pacific time, but is recorded Monday through Wednesday at 4:30 p.m., and Thursdays at 3:30 p.m and 6:00 p.m. The second Thursday episode usually airs on Friday of that week.\n\nIn 2002, Late Show with David Letterman was ranked No. 7 on TV Guide's 50 Greatest TV Shows of All Time. CBS has a contract with Worldwide Pants to continue the show through 2014; by then, Letterman will surpass Johnny Carson as the longest tenured late-night talk show host.","popularity":430.9679,"poster_path":"/fTBC5EpsgKmli9VQcJMtqQ08Qj4.jpg","first_air_date":"1993-08-30","name":"Late Show with David Letterman","vote_average":6.325,"vote_count":154},{"adult":false,"backdrop_path":"/mSkisNewxu55Ivar5EubhcIuoqn.jpg","genre_ids":[10764],"id":30957,"origin_country":["US","GB"],"original_language":"en","original_name":"The Amazing Race","overview":"This reality competition sees teams embark on a trek around the world to amazing destinations where they must compete in a series of challenges, some mental and some physical. Only when the tasks are completed will they learn of their next location. Teams who are the farthest behind will gradually be eliminated as the contest progresses, with the first team to arrive at the final destination winning the race and the $1 million prize.","popularity":470.7293,"poster_path":"/x1jq0atcQg6UkaZpco0kFL6QHuM.jpg","first_air_date":"2001-09-05","name":"The Amazing Race","vote_average":6.873,"vote_count":153},{"adult":false,"backdrop_path":"/gMMnf8VRg3Z98WaFmOLr9Jk8pIs.jpg","genre_ids":[35,10767],"id":63770,"origin_country":["US"],"original_language":"en","original_name":"The Late Show with Stephen Colbert","overview":"Stephen Colbert brings his signature satire and comedy to The Late Show with Stephen Colbert, the #1 show in late night, where he talks with an eclectic mix of guests about what is new and relevant in the worlds of politics, entertainment, business, music, technology, and more. Featuring bandleader Jon Batiste with his band Stay Human, the Emmy Award-nominated show is broadcast from the historic Ed Sullivan Theater. Stephen Colbert, Chris Licht, Tom Purcell, and Jon Stewart are executive producers. Barry Julien and Denise Rehrig serve as co-executive producers.must watch","popularity":446.8992,"poster_path":"/9jkThAGYj2yp8jsS6Nriy5mzKFT.jpg","first_air_date":"2015-09-08","name":"The Late Show with Stephen Colbert","vote_average":6.355,"vote_count":310},{"adult":false,"backdrop_path":"/fgvM6m7gAd8kDAaLF16aflbOSAK.jpg","genre_ids":[18],"id":1416,"origin_country":["US"],"original_language":"en","original_name":"Grey's Anatomy","overview":"Follows the personal and professional lives of a group of doctors at Seattle’s Grey Sloan Memorial Hospital.","popularity":456.262,"poster_path":"/7jEVqXC14bhfAzSPgr896dMdDv6.jpg","first_air_date":"2005-03-27","name":"Grey's Anatomy","vote_average":8.225,"vote_count":10542},{"adult":false,"backdrop_path":"/oJuDMcM8LZA5F5Ahgc9mZg2LRIO.jpg","genre_ids":[16,35],"id":32726,"origin_country":["US"],"original_language":"en","original_name":"Bob's Burgers","overview":"Bob's Burgers follows a third-generation restaurateur, Bob, as he runs Bob's Burgers with the help of his wife and their three kids. Bob and his quirky family have big ideas about burgers, but fall short on service and sophistication. Despite the greasy counters, lousy location and a dearth of customers, Bob and his family are determined to make Bob's Burgers \"grand re-re-re-opening\" a success.","popularity":324.9696,"poster_path":"/yVz5foNr6nCfathj0igg8RLVGfn.jpg","first_air_date":"2011-01-09","name":"Bob's Burgers","vote_average":7.824,"vote_count":992},{"adult":false,"backdrop_path":"/iEg2LHsFV3vC6LywkBAL3c1n9PP.jpg","genre_ids":[10767,35],"id":61818,"origin_country":["US"],"original_language":"en","original_name":"Late Night with Seth Meyers","overview":"Seth Meyers, who is \"Saturday Night Live’s\" longest serving anchor on the show’s wildly popular \"Weekend Update,\" takes over as host of NBC’s \"Late Night\" — home to A-list celebrity guests, memorable comedy and the best in musical talent. As the Emmy Award-winning head writer for \"SNL,\" Meyers has established a reputation for sharp wit and perfectly timed comedy, and has gained fame for his spot-on jokes and satire. Meyers takes his departure from \"SNL\" to his new post at \"Late Night,\" as Jimmy Fallon moves to \"The Tonight Show\".","popularity":443.8456,"poster_path":"/rw0QaegwgKbRoB2CZe2lfewltT9.jpg","first_air_date":"2014-02-25","name":"Late Night with Seth Meyers","vote_average":5.333,"vote_count":108},{"adult":false,"backdrop_path":"/6jGVOu5NvnmSKh28ByWAJrTOEH2.jpg","genre_ids":[35,10767],"id":59941,"origin_country":["US"],"original_language":"en","original_name":"The Tonight Show Starring Jimmy Fallon","overview":"After Jay Leno's second retirement from the program, Jimmy Fallon stepped in as his permanent replacement. After 42 years in Los Angeles the program was brought back to New York.","popularity":424.6807,"poster_path":"/g4amxJvtpnY79J77xeamnAEUO8r.jpg","first_air_date":"2014-02-17","name":"The Tonight Show Starring Jimmy Fallon","vote_average":5.865,"vote_count":341},{"adult":false,"backdrop_path":"/9daf0KXr3xUkMt2NCI0ZhDIZJEa.jpg","genre_ids":[10766],"id":12415,"origin_country":["ZA"],"original_language":"af","original_name":"Egoli: Place of Gold","overview":"A South African television soap opera created by Franz Marx which revolves around the daily ups, downs, trials and tribulations of a handful of families in and around Johannesburg (which is often referred to as eGoli - the City of Gold)","popularity":218.0737,"poster_path":"/5X0SWyNJ5IjN9YSXlbHBOVMzh1G.jpg","first_air_date":"1992-04-06","name":"Egoli: Place of Gold","vote_average":6.8,"vote_count":4},{"adult":false,"backdrop_path":"/hqqdoXdrp4o8ZqADHVYIXwBkn3Y.jpg","genre_ids":[10759,16,35,10765,10762,10751],"id":65733,"origin_country":["JP"],"original_language":"ja","original_name":"ドラえもん","overview":"Robotic cat Doraemon is sent back in time from the 22nd century to protect 10-year-old Noby, a lazy and uncoordinated boy who is destined to have a tragic future. Doraemon can create secret gadgets from a pocket on his stomach, but they usually cause more bad than good because of Noby's propensity to misuse them.","popularity":433.9426,"poster_path":"/9ZN1P32SHviL3SV51qLivxycvcx.jpg","first_air_date":"2005-04-22","name":"Doraemon","vote_average":8.1,"vote_count":179},{"adult":false,"backdrop_path":"/lksigd4PnpvvIY9oPHW2DEnHh5H.jpg","genre_ids":[],"id":70558,"origin_country":["US"],"original_language":"en","original_name":"NPR Tiny Desk Concerts","overview":"Intimate musical performances, recorded live at the desk of All Songs Considered host Bob Boilen.","popularity":337.0835,"poster_path":"/sJ6HdzajIVkC5G2kRROhNu8at43.jpg","first_air_date":"2008-04-22","name":"NPR Tiny Desk Concerts","vote_average":7.8,"vote_count":8},{"adult":false,"backdrop_path":"/tLccUh3uazZ9TkLhe53UwprJhI4.jpg","genre_ids":[80,18,10759],"id":32798,"origin_country":["US"],"original_language":"en","original_name":"Hawaii Five-0","overview":"Steve McGarrett returns home to Oahu, in order to find his father's killer. The governor offers him the chance to run his own task force (Five-0). Steve's team is joined by Chin Ho Kelly, Danny \"Danno\" Williams, and Kono Kalakaua.","popularity":369.7408,"poster_path":"/sIdCKlmM2nU4akIvFQaAIiU8YES.jpg","first_air_date":"2010-09-20","name":"Hawaii Five-0","vote_average":7.754,"vote_count":1775},{"adult":false,"backdrop_path":"/9kuUPHz99Oojm6GG7mawtIjv4lv.jpg","genre_ids":[10764],"id":331,"origin_country":["US"],"original_language":"en","original_name":"America's Next Top Model","overview":"Aspiring models compete for a chance to break into the business with a panel of judges critiquing their progress throughout the competition.","popularity":338.6329,"poster_path":"/47EIfjYrT80AOfpAIkvSxdpwGOv.jpg","first_air_date":"2003-05-20","name":"America's Next Top Model","vote_average":5.3,"vote_count":133}],"total_pages":10004,"total_results":200080}

In [9]:
pd.DataFrame(response.json()['results'])

,adult,backdrop_path,genre_ids,id,origin_country,original_language,original_name,overview,popularity,poster_path,first_air_date,name,vote_average,vote_count
0,False,/hHMWfDlqKisD5zVcZfz3KEw5U3v.jpg,"[18, 10751]",50821,[HU],hu,Barátok közt,Miklós introduces viewers into the world of Mo...,675.4330,/kBBbSgNchtMvsgD6z1oI1RRluHP.jpg,1998-10-26,Among Friends,3.200,14
1,False,/qLMfcvdCcCGD2BNLH8b6ZCBuO7D.jpg,"[10763, 35]",2224,[US],en,The Daily Show,The World's Fakest News Team tackle the bigges...,763.3525,/ixcfyK7it6FjRM36Te4OdblAq4X.jpg,1996-07-22,The Daily Show,6.363,578
2,False,/m0bV3qBiJBBlpFaaKjwHo13MVjm.jpg,"[35, 10767]",14981,[US],en,The Late Late Show with Craig Ferguson,The Late Late Show with Craig Ferguson is an A...,770.8415,/gGC7zSDgG0FY0MbM1pjfhTCWQBI.jpg,2005-01-03,The Late Late Show with Craig Ferguson,6.785,107
3,False,/kA50bkSC6bw5ZkutYrN9sLD9CZ9.jpg,"[10767, 35]",22980,[US],en,Watch What Happens Live with Andy Cohen,Bravo network executive Andy Cohen discusses p...,560.8859,/onSD9UXfJwrMXWhq7UY7hGF2S1h.jpg,2009-07-16,Watch What Happens Live with Andy Cohen,5.136,77
4,False,/kkfqNkGQR5og5sDjJTxTVmI9PW.jpg,"[80, 18, 10766]",72879,[FR],fr,Demain nous appartient,"The story revolves around the people of Sète, ...",552.9920,/zMWldNZF0wS3L5XkDVFHxYhclcL.jpg,2017-07-17,Tomorrow Is Ours,6.343,67
5,False,/Ajku4m7jbMpCTEPr794Imv19mCA.jpg,"[10763, 35]",4385,[US],en,The Colbert Report,The Colbert Report is an American satirical la...,534.6319,/pn2CVXjOlR8kY5MgOTJjZ71IM0Q.jpg,2005-10-17,The Colbert Report,6.862,276
6,False,/hvFCS0dMeC3ffiF4uYTKzUAkvYL.jpg,[35],65701,[US],en,Good Mythical Morning,"Two ""Internetainers"" (Rhett & Link) go far out...",440.6367,/jMpBQr2aNOFAI6wsC47zsOG6qOh.jpg,2012-01-09,Good Mythical Morning,7.038,80
7,False,/92cc2hINaW72HTA0RqQaqPUbl4g.jpg,"[16, 35, 10767]",46825,[US],en,Rooster Teeth Animated Adventures,The animated shenanigans of the Rooster Teeth ...,407.6910,/xrcOsjmuBcmf1YhqyQ6qrGCcsvE.jpg,2011-09-28,Rooster Teeth Animated Adventures,8.600,5
8,False,/7jEnft2CLNbILWAiBRIBrXNN7Qh.jpg,"[10767, 35]",498,[US],en,Late Show with David Letterman,Late Show with David Letterman is an American ...,430.9679,/fTBC5EpsgKmli9VQcJMtqQ08Qj4.jpg,1993-08-30,Late Show with David Letterman,6.325,154
9,False,/mSkisNewxu55Ivar5EubhcIuoqn.jpg,[10764],30957,"[US, GB]",en,The Amazing Race,This reality competition sees teams embark on ...,470.7293,/x1jq0atcQg6UkaZpco0kFL6QHuM.jpg,2001-09-05,The Amazing Race,6.873,153
10,False,/gMMnf8VRg3Z98WaFmOLr9Jk8pIs.jpg,"[35, 10767]",63770,[US],en,The Late Show with Stephen Colbert,Stephen Colbert brings his signature satire an...,446.8992,/9jkThAGYj2yp8jsS6Nriy5mzKFT.jpg,2015-09-08,The Late Show with Stephen Colbert,6.355,310
11,False,/fgvM6m7gAd8kDAaLF16aflbOSAK.jpg,[18],1416,[US],en,Grey's Anatomy,Follows the personal and professional lives of...,456.2620,/7jEVqXC14bhfAzSPgr896dMdDv6.jpg,2005-03-27,Grey's Anatomy,8.225,10542
12,False,/oJuDMcM8LZA5F5Ahgc9mZg2LRIO.jpg,"[16, 35]",32726,[US],en,Bob's Burgers,Bob's Burgers follows a third-generation resta...,324.9696,/yVz5foNr6nCfathj0igg8RLVGfn.jpg,2011-01-09,Bob's Burgers,7.824,992
13,False,/iEg2LHsFV3vC6LywkBAL3c1n9PP.jpg,"[10767, 35]",61818,[US],en,Late Night with Seth Meyers,"Seth Meyers, who is ""Saturday Night Live’s"" lo...",443.8456,/rw0QaegwgKbRoB2CZe2lfewltT9.jpg,2014-02-25,Late Night with Seth Meyers,5.333,108
14,False,/6jGVOu5NvnmSKh28ByWAJrTOEH2.jpg,"[35, 10767]",59941,[US],en,The Tonight Show Starring Jimmy Fallon,After Jay Leno's second retirement from the pr...,424.6807,/g4amxJvtpnY79J77xeamnAEUO8r.jpg,2014-02-17,The Tonight Show Starring Jimmy Fallon,5.865,341
15,False,/9daf0KXr3xUkMt2NCI0ZhDIZJEa.jpg,[10766],12415,[ZA],af,Egoli: Place of Gold,A South African television soap opera created ...,218.0737,/5X0SWyNJ5IjN9YSXlbHBOVMzh1G.jpg,1992-04-06,Egoli: Place of Gold,6.800,4
16,False,/hqqdoXdrp4o8ZqADHVYIXwBkn3Y.jpg,"[10759, 16, 35, 10765, 10762, 10751]",65733,[JP],ja,ドラえもん,Robotic cat Doraemon is sent back in time from...,433.9426,/9ZN1P32SHviL3SV51qLivxycvcx.jpg,2005-04-22,Doraemon,8.100,179
17,False,/lksigd4PnpvvIY9oPHW2DEnHh5H.jpg,[],70558,[US],en,NPR Tiny Desk Concerts,"Intimate musical performances, recorded live a...",337.0835,/sJ6HdzajIVkC5G2kRROhNu8at43.jpg,2008-04-22,NPR Tiny Desk Concerts,7.800,8
18,False,/tLccUh3uazZ9TkLhe53UwprJhI4.jpg,"[80, 18, 10759]",32798,[US],en,Hawaii Five-0,"Steve McGarrett returns home to Oahu, in order...",369.7408,/sIdCKlmM2nU4akIvFQaAIiU8YES.jpg,2010-09-20,Hawaii Five-0,7.754,1775
19,False,/9kuUPHz99Oojm6GG7mawtIjv4lv.jpg,[10764],331,[US],en,America's Next Top Model,Aspiring models compete for a chance to break ...,338.6329,/47EIfjYrT80AOfpAIkvSxdpwGOv.jpg,2003-05-20,America's Next Top Model,5.300,133

In [11]:
import requests

url = "https://api.themoviedb.org/3/movie/popular?language=en-US&page=1"

headers = {
    "accept": "application/json",
    "Authorization": "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI0YWUxZjFkZTIxM2MyMTZjMTFlOWI1MGVmYjgxYjAwNCIsIm5iZiI6MTc1MDcwMDk4MC41MjQsInN1YiI6IjY4NTk5M2I0OWY3ZTZkMzQ2ZTc5Njk1ZSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.wTJ9I_7Ye1p5b4BkUCdHFhOYwC4Mf_s8Y8mELXkVaMg"
}

response = requests.get(url, headers=headers)

print(response.text)

{"page":1,"results":[{"adult":false,"backdrop_path":"/uIpJPDNFoeX0TVml9smPrs9KUVx.jpg","genre_ids":[27,9648],"id":574475,"original_language":"en","original_title":"Final Destination Bloodlines","overview":"Plagued by a violent recurring nightmare, college student Stefanie heads home to track down the one person who might be able to break the cycle and save her family from the grisly demise that inevitably awaits them all.","popularity":954.9084,"poster_path":"/6WxhEvFsauuACfv8HyoVX6mZKFj.jpg","release_date":"2025-05-14","title":"Final Destination Bloodlines","video":false,"vote_average":7.221,"vote_count":1235},{"adult":false,"backdrop_path":"/7Zx3wDG5bBtcfk8lcnCWDOLM4Y4.jpg","genre_ids":[10751,878,35,12],"id":552524,"original_language":"en","original_title":"Lilo & Stitch","overview":"The wildly funny and touching story of a lonely Hawaiian girl and the fugitive alien who helps to mend her broken family.","popularity":423.2966,"poster_path":"/7c5VBuCbjZOk7lSfj9sMpmDIaKX.jpg","release_date":"2025-05-17","title":"Lilo & Stitch","video":false,"vote_average":7.104,"vote_count":709},{"adult":false,"backdrop_path":"/zxjFabSJKMAvuu3acNg78nuTuCs.jpg","genre_ids":[28,53,27],"id":1442776,"original_language":"zh","original_title":"Kuang Bao Ju Xi","overview":"A young man climbs into the mountains to pick up a meteorite that has fallen there and is killed by something. The \"thing\" descends to the village and begins to eat the inhabitants one by one, terrorizing the entire island.","popularity":435.9359,"poster_path":"/9TFaFsSXedaALXTzba349euDeoY.jpg","release_date":"2024-03-27","title":"Crazy Lizard","video":false,"vote_average":5.583,"vote_count":12},{"adult":false,"backdrop_path":"/xtnfoFs9vOLBF7Ox13mFmFUovey.jpg","genre_ids":[28,12,18],"id":1311844,"original_language":"en","original_title":"The Twisters","overview":"A deadly patchwork of destructive cyclones is on an apocalyptic path of convergence at a populated Midwest city center. There, the twisters will merge into one mega tornado that threatens to obliterate the cities for hundreds of miles around.","popularity":450.7672,"poster_path":"/8OP3h80BzIDgmMNANVaYlQ6H4Oc.jpg","release_date":"2024-06-28","title":"The Twisters","video":false,"vote_average":5.368,"vote_count":19},{"adult":false,"backdrop_path":"/v47JpEeMlO0zNWCngouh0MafchU.jpg","genre_ids":[878,35,28],"id":605722,"original_language":"en","original_title":"Distant","overview":"After crash-landing on an alien planet, an asteroid miner must contend with the challenges of his new surroundings, while making his way across the harsh terrain to the only other survivor – a woman who is trapped in her escape pod.","popularity":393.346,"poster_path":"/czh8HOhsbBUKoKsmRmLQMCLHUev.jpg","release_date":"2024-07-12","title":"Distant","video":false,"vote_average":6.23,"vote_count":128},{"adult":false,"backdrop_path":"/9f06S7Uc1Xmnc3OYtK8UKu9o3Ox.jpg","genre_ids":[28,12,27],"id":1181039,"original_language":"zh","original_title":"鬼吹灯：献王虫谷","overview":"Adapted from the 3rd volume in the novel series \"Candle in the Tomb\" by Zhang Mu Ye. Hu Bayi, Wang Kaixuan, and Shiely Yang, infected with a curse, embark on a journey to King Xian's tomb to retrieve the Haochen Bead and break the curse. They face ancient organs, ghostly visions, explosive bugs, and a massive salamander.","popularity":373.627,"poster_path":"/7Hk1qxAvZi9H9cfBb4iHkoGjapH.jpg","release_date":"2023-09-22","title":"Candle in the Tomb: The Worm Valley","video":false,"vote_average":6.3,"vote_count":10},{"adult":false,"backdrop_path":"/7HqLLVjdjhXS0Qoz1SgZofhkIpE.jpg","genre_ids":[14,10751,28],"id":1087192,"original_language":"en","original_title":"How to Train Your Dragon","overview":"On the rugged isle of Berk, where Vikings and dragons have been bitter enemies for generations, Hiccup stands apart, defying centuries of tradition when he befriends Toothless, a feared Night Fury dragon. Their unlikely bond reveals the true nature of dragons, challenging the very foundations of Viking society.","popularity":360.4246,"poster_path":"/q5pXRYTycaeW6dEgsCrd4mYPmxM.jpg","release_date":"2025-06-06","title":"How to Train Your Dragon","video":false,"vote_average":7.965,"vote_count":396},{"adult":false,"backdrop_path":"/6e8Ldi2Wo5W5iF8PEhb1K3dC8TK.jpg","genre_ids":[53,28],"id":1087891,"original_language":"en","original_title":"The Amateur","overview":"After his life is turned upside down when his wife is killed in a London terrorist attack, a brilliant but introverted CIA decoder takes matters into his own hands when his supervisors refuse to take action.","popularity":263.2979,"poster_path":"/SNEoUInCa5fAgwuEBMIMBGvkkh.jpg","release_date":"2025-04-09","title":"The Amateur","video":false,"vote_average":6.961,"vote_count":612},{"adult":false,"backdrop_path":"/wnnu8htEZBLtwrke9QYfLKx6zjp.jpg","genre_ids":[53,18,80],"id":1426776,"original_language":"en","original_title":"STRAW","overview":"What will be her last straw? A devastatingly bad day pushes a hardworking single mother to the breaking point — and into a shocking act of desperation.","popularity":257.1925,"poster_path":"/t3cmnXYtxJb9vVL1ThvT2CWSe1n.jpg","release_date":"2025-06-05","title":"STRAW","video":false,"vote_average":7.991,"vote_count":611},{"adult":false,"backdrop_path":"/6WqqEjiycNvDLjbEClM1zCwIbDD.jpg","genre_ids":[27,53,878],"id":1100988,"original_language":"en","original_title":"28 Years Later","overview":"Twenty-eight years since the rage virus escaped a biological weapons laboratory, now, still in a ruthlessly enforced quarantine, some have found ways to exist amidst the infected. One such group lives on a small island connected to the mainland by a single, heavily-defended causeway. When one member departs on a mission into the dark heart of the mainland, he discovers secrets, wonders, and horrors that have mutated not only the infected but other survivors as well.","popularity":291.3007,"poster_path":"/giAiJSwOJcfA8Y4PCNMGAhfTSyA.jpg","release_date":"2025-06-18","title":"28 Years Later","video":false,"vote_average":7.2,"vote_count":226},{"adult":false,"backdrop_path":"/fPWJn5pqBr8n4h0YxW3QuasdvoI.jpg","genre_ids":[28,53],"id":1127110,"original_language":"en","original_title":"Diablo","overview":"Ex-con Kris Chaney seizes the daughter of a Colombian gangster to fulfill a noble promise to the young girl's mother. When her father enlists both the criminal underworld and a psychotic killer to exact his revenge, Kris relies on everything he's ever learned to stay alive and keep his word.","popularity":275.7111,"poster_path":"/uFQduVyYIinJy3eLjozgfl6Xtcn.jpg","release_date":"2025-06-13","title":"Diablo","video":false,"vote_average":7.0,"vote_count":44},{"adult":false,"backdrop_path":"/eRNMOrA6Bigonug3dT1R7aLZQaq.jpg","genre_ids":[28],"id":1240475,"original_language":"zh","original_title":"缉恶","overview":"The film tells the story of narcotics police officer Huang Mingjin and the \"mysterious figure\" Wei Yunzhou. Through completely different means and methods, in the process of calculating and wrestling with each other, they tear apart the facade of urban tranquility, exposing the underground drug network woven by the hidden hand \"Long Wang\", and ultimately eradicate the darkness with the sword of justice, revealing the dawn of light.","popularity":187.8974,"poster_path":"/m5UBHbEjQJx3AkRZWRY6A4l4ZDT.jpg","release_date":"2024-02-12","title":"Hunt the Wicked","video":false,"vote_average":5.444,"vote_count":9},{"adult":false,"backdrop_path":"/rJjhOuRFldNF0OWSuSk4PiCLmeA.jpg","genre_ids":[16,14,28,35,10402],"id":803796,"original_language":"en","original_title":"KPop Demon Hunters","overview":"When K-pop superstars Rumi, Mira and Zoey aren't selling out stadiums, they're using their secret powers to protect their fans from supernatural threats.","popularity":253.5625,"poster_path":"/jfS5KEfiwsS35ieZvdUdJKkwLlZ.jpg","release_date":"2025-06-20","title":"KPop Demon Hunters","video":false,"vote_average":8.786,"vote_count":110},{"adult":false,"backdrop_path":"/a3F9cXjRH488qcOqFmFZwqawBMU.jpg","genre_ids":[16,28,878],"id":1376434,"original_language":"en","original_title":"Predator: Killer of Killers","overview":"While three of the fiercest warriors in human history—a Viking raider, a ninja in feudal Japan, and a WWII pilot—are killers in their own right, they are merely prey for their new opponent: the ultimate killer of killers.","popularity":186.3722,"poster_path":"/2XDQa6EmFHSA37j1t0w88vpWqj9.jpg","release_date":"2025-06-05","title":"Predator: Killer of Killers","video":false,"vote_average":7.985,"vote_count":590},{"adult":false,"backdrop_path":"/yBDvgpyynDsbMyK21FoQu1c2wYR.jpg","genre_ids":[9648,80,53],"id":870028,"original_language":"en","original_title":"The Accountant²","overview":"When an old acquaintance is murdered, Wolff is compelled to solve the case. Realizing more extreme measures are necessary, Wolff recruits his estranged and highly lethal brother, Brax, to help. In partnership with Marybeth Medina, they uncover a deadly conspiracy, becoming targets of a ruthless network of killers who will stop at nothing to keep their secrets buried.","popularity":178.2627,"poster_path":"/kMDUS7VmFhb2coRfVBoGLR8ADBt.jpg","release_date":"2025-04-23","title":"The Accountant²","video":false,"vote_average":7.209,"vote_count":923},{"adult":false,"backdrop_path":"/2Nti3gYAX513wvhp8IiLL6ZDyOm.jpg","genre_ids":[10751,35,12,14],"id":950387,"original_language":"en","original_title":"A Minecraft Movie","overview":"Four misfits find themselves struggling with ordinary problems when they are suddenly pulled through a mysterious portal into the Overworld: a bizarre, cubic wonderland that thrives on imagination. To get back home, they'll have to master this world while embarking on a magical quest with an unexpected, expert crafter, Steve.","popularity":183.7288,"poster_path":"/yFHHfHcUgGAxziP1C3lLt0q2T4s.jpg","release_date":"2025-03-31","title":"A Minecraft Movie","video":false,"vote_average":6.492,"vote_count":1884},{"adult":false,"backdrop_path":"/nAxGnGHOsfzufThz20zgmRwKur3.jpg","genre_ids":[27,14,53],"id":1233413,"original_language":"en","original_title":"Sinners","overview":"Trying to leave their troubled lives behind, twin brothers return to their hometown to start again, only to discover that an even greater evil is waiting to welcome them back.","popularity":180.8826,"poster_path":"/yqsCU5XOP2mkbFamzAqbqntmfav.jpg","release_date":"2025-04-16","title":"Sinners","video":false,"vote_average":7.558,"vote_count":1628},{"adult":false,"backdrop_path":"/lOje1iz4VYWELYWRkZAwI7oIJd0.jpg","genre_ids":[28,35,80],"id":1239193,"original_language":"en","original_title":"Deep Cover","overview":"Kat is an improv comedy teacher beginning to question if she’s missed her shot at success. When an undercover cop offers her the role of a lifetime, she recruits two of her students to infiltrate London’s gangland by impersonating dangerous criminals.","popularity":149.5605,"poster_path":"/euM8fJvfH28xhjGy25LiygxfkWc.jpg","release_date":"2025-06-12","title":"Deep Cover","video":false,"vote_average":6.761,"vote_count":203},{"adult":false,"backdrop_path":"/4uEVhE07sSEg3t9MdudCjXWt9fG.jpg","genre_ids":[27],"id":1152619,"original_language":"en","original_title":"Possessions","overview":"Follows a father who seeks a fresh start with his son after the loss of his wife, and purchased a storage unit facility sight unseen, but secrets buried behind the metal doors become a parent's worst nightmare.","popularity":162.1438,"poster_path":"/39a7zYZvkGfs7EOVVK3dQlWyYJ0.jpg","release_date":"2024-04-12","title":"Possessions","video":false,"vote_average":4.4,"vote_count":22},{"adult":false,"backdrop_path":"/7TIoq6DRnMn2aDViSRfPooWZkga.jpg","genre_ids":[28,18,53],"id":1289601,"original_language":"en","original_title":"Life After Fighting","overview":"Retired martial arts world champion Alex Faulkner has settled into a simple life, when the disappearance of two of his students leads to an unthinkable discovery close to home. Just when all hope of finding the children is lost, he locates the imprisoned girls and unsurfaces an international child trafficking operation, which draws him back into the fight of his life against those behind it.","popularity":135.6977,"poster_path":"/uKWAk4BHzyEOMmLKUDXoIAPhH36.jpg","release_date":"2024-06-07","title":"Life After Fighting","video":false,"vote_average":7.045,"vote_count":44}],"total_pages":51060,"total_results":1021191}

In [13]:
temp_df=pd.DataFrame(response.json()["results"])

In [21]:
df=pd.DataFrame()

In [25]:
import requests
for i in range(1,500):
    url = f"https://api.themoviedb.org/3/movie/popular?language=en-US&page={i}"
    headers = {
        "accept": "application/json",
        "Authorization": "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI0YWUxZjFkZTIxM2MyMTZjMTFlOWI1MGVmYjgxYjAwNCIsIm5iZiI6MTc1MDcwMDk4MC41MjQsInN1YiI6IjY4NTk5M2I0OWY3ZTZkMzQ2ZTc5Njk1ZSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.wTJ9I_7Ye1p5b4BkUCdHFhOYwC4Mf_s8Y8mELXkVaMg"
    }
    
    response = requests.get(url, headers=headers)
    temp_df=pd.DataFrame(response.json()["results"])
    df = pd.concat([df, temp_df], ignore_index=True)

ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))