In [1]:
import pandas as pd

In [2]:
df=pd.read_json(r"C:\Users\Asus\Downloads\DS_Datasets\train.json")

In [3]:
df

          id      cuisine                                        ingredients
0      10259        greek  [romaine lettuce, black olives, grape tomatoes...
1      25693  southern_us  [plain flour, ground pepper, salt, tomatoes, g...
2      20130     filipino  [eggs, pepper, salt, mayonaise, cooking oil, g...
3      22213       indian                [water, vegetable oil, wheat, salt]
4      13162       indian  [black pepper, shallots, cornflour, cayenne pe...
...      ...          ...                                                ...
39769  29109        irish  [light brown sugar, granulated sugar, butter, ...
39770  11462      italian  [KRAFT Zesty Italian Dressing, purple onion, b...
39771   2238        irish  [eggs, citrus fruit, raisins, sourdough starte...
39772  41882      chinese  [boneless chicken skinless thigh, minced garli...
39773   2362      mexican  [green chile, jalapeno chilies, onions, ground...

[39774 rows x 3 columns]

In [4]:
#pandas.read_json(path_or_buf, *, orient=None, typ='frame', dtype=None, convert_axes=None, convert_dates=True, keep_default_dates=True, precise_float=False, date_unit=None, encoding=None, encoding_errors='strict', lines=False, chunksize=None, compression='infer', nrows=None, storage_options=None, dtype_backend=<no_default>, engine='ujson')

In [9]:
f1=pd.read_json('https://api.exchangerate-api.com/v4/latest/INR')

In [11]:
f1

,provider,WARNING_UPGRADE_TO_V6,terms,base,date,time_last_updated,rates
INR,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2025-06-23,1750636801,1.0000
AED,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2025-06-23,1750636801,0.0424
AFN,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2025-06-23,1750636801,0.8160
ALL,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2025-06-23,1750636801,0.9810
AMD,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2025-06-23,1750636801,4.4500
...,...,...,...,...,...,...,...
XPF,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2025-06-23,1750636801,1.2000
YER,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2025-06-23,1750636801,2.8000
ZAR,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2025-06-23,1750636801,0.2090
ZMW,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2025-06-23,1750636801,0.2670
ZWL,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2025-06-23,1750636801,0.3110

In [13]:
#!pip install mysql.connector

In [15]:
import mysql.connector

In [17]:
con=mysql.connector.connect(host='localhost',user='root',password='Hemant@123',database='aliens')

In [19]:
# mycusrcor=con.cursor()

In [21]:
# mycusrcor.execute("select * from student")

In [35]:
# for i in mycusrcor:
#     print(i)

In [35]:
# pip install --upgrade mysql-connector-python

In [37]:
df=pd.read_sql_query("select * from student",con)

C:\Users\Asus\AppData\Local\Temp\ipykernel_8208\617124653.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df=pd.read_sql_query("select * from student",con)

In [39]:
df

   idx Student_Name  Age  Marks
0    1       Hemant   23     99
1    2       sakshi   25    100
2    3       poonam   26     98
3    4     prashant   21     99
4    5       Adarsh   27    100
5    6       piyush   20     96