In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
%matplotlib inline

In [2]:
df=pd.read_csv(r"C:\Users\GR0012AU\Downloads\train.csv")

In [3]:
df.sample(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
736,737,0,3,"Ford, Mrs. Edward (Margaret Ann Watson)",female,48.0,1,3,W./C. 6608,34.3750,NaN,S
370,371,1,1,"Harder, Mr. George Achilles",male,25.0,1,0,11765,55.4417,E50,C
160,161,0,3,"Cribb, Mr. John Hatfield",male,44.0,0,1,371362,16.1000,NaN,S
632,633,1,1,"Stahelin-Maeglin, Dr. Max",male,32.0,0,0,13214,30.5000,B50,C
221,222,0,2,"Bracken, Mr. James H",male,27.0,0,0,220367,13.0000,NaN,S

In [4]:
df.drop(columns=["PassengerId","Name","Ticket","Cabin"],inplace=True)

In [5]:
df.sample(5)

     Survived  Pclass     Sex   Age  SibSp  Parch      Fare Embarked
730         1       1  female  29.0      0      0  211.3375        S
756         0       3    male  28.0      0      0    7.7958        S
473         1       2  female  23.0      0      0   13.7917        C
871         1       1  female  47.0      1      1   52.5542        S
448         1       3  female   5.0      2      1   19.2583        C

In [6]:
df1=df.copy()

In [7]:
df1["family"]=df["SibSp"]+df["Parch"]

In [8]:
df1.drop(columns=["SibSp","Parch"],inplace=True)

In [9]:
df1.sample(5)

     Survived  Pclass     Sex   Age    Fare Embarked  family
79          1       3  female  30.0  12.475        S       0
98          1       2  female  34.0  23.000        S       1
419         0       3  female  10.0  24.150        S       2
722         0       2    male  34.0  13.000        S       0
24          0       3  female   8.0  21.075        S       4

In [10]:
df.shape

(891, 8)

In [11]:
df.size

7128

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Survived  891 non-null    int64
 1   Pclass    891 non-null    int64
 2   Sex       891 non-null    object
 3   Age       714 non-null    float64
 4   SibSp     891 non-null    int64
 5   Parch     891 non-null    int64
 6   Fare      891 non-null    float64
 7   Embarked  889 non-null    object
dtypes: float64(2), int64(4), object(2)
memory usage: 55.8+ KB

In [13]:
df.isnull().sum()

Survived      0
Pclass        0
Sex           0
Age         177
SibSp         0
Parch         0
Fare          0
Embarked      2
dtype: int64

In [14]:
df.describe()

         Survived      Pclass         Age       SibSp       Parch        Fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [15]:
df.duplicated().sum()

111

In [16]:
df.corr()

          Survived    Pclass       Age     SibSp     Parch      Fare
Survived  1.000000 -0.338481 -0.077221 -0.035322  0.081629  0.257307
Pclass   -0.338481  1.000000 -0.369226  0.083081  0.018443 -0.549500
Age      -0.077221 -0.369226  1.000000 -0.308247 -0.189119  0.096067
SibSp    -0.035322  0.083081 -0.308247  1.000000  0.414838  0.159651
Parch     0.081629  0.018443 -0.189119  0.414838  1.000000  0.216225
Fare      0.257307 -0.549500  0.096067  0.159651  0.216225  1.000000

In [17]:
dependent_columns=df1["Survived"]

In [18]:
independent_columns=df1.iloc[:,1:]

In [19]:
independent_columns.sample(5)

     Pclass     Sex   Age      Fare Embarked  family
577       1  female  39.0   55.9000        S       1
793       1    male   NaN   30.6958        C       0
291       1  female  19.0   91.0792        C       1
758       3    male  34.0    8.0500        S       0
698       1    male  49.0  110.8833        C       2

In [20]:
dependent_columns.sample(5)

521    0
756    0
603    0
423    0
91     0
Name: Survived, dtype: int64

In [21]:
from sklearn.model_selection import train_test_split

In [22]:
x_train,x_test,y_train,y_test=train_test_split(independent_columns,dependent_columns,test_size=0.3,random_state=0)

In [23]:
x_train

     Pclass     Sex   Age     Fare Embarked  family
857       1    male  51.0  26.5500        S       0
52        1  female  49.0  76.7292        C       1
386       3    male   1.0  46.9000        S       7
124       1    male  54.0  77.2875        S       1
578       3  female   NaN  14.4583        C       1
..      ...     ...   ...      ...      ...     ...
835       1  female  39.0  83.1583        C       2
192       3  female  19.0   7.8542        S       1
629       3    male   NaN   7.7333        Q       0
559       3  female  36.0  17.4000        S       1
684       2    male  60.0  39.0000        S       2

[623 rows x 6 columns]

In [24]:
from sklearn.impute import SimpleImputer
SI=SimpleImputer(strategy="most_frequent")

x_train_age=pd.DataFrame(SI.fit_transform(x_train[["Age"]]),columns=["Age"])
x_train_embarked=pd.DataFrame(SI.fit_transform(x_train[["Embarked"]]),columns=["Age"])

x_test_age=pd.DataFrame(SI.fit_transform(x_test[["Age"]]),columns=["Age"])
x_test_embarked=pd.DataFrame(SI.fit_transform(x_test[["Embarked"]]),columns=["Age"])

In [25]:
from sklearn.preprocessing import OneHotEncoder

OHE_sex=OneHotEncoder(drop="first",sparse=False)
x_train_sex=OHE_sex.fit_transform(x_train[["Sex"]])
x_test_sex=OHE_sex.fit_transform(x_test[["Sex"]])

In [26]:
x_train_sex.shape

(623, 1)

In [27]:
x_train["Pclass"].values.reshape(623,1)

array([[1],
       [1],
       [3],
       [1],
       [3],
       [2],
       [1],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [1],
       [1],
       [3],
       [3],
       [3],
       [3],
       [2],
       [1],
       [2],
       [2],
       [3],
       [2],
       [2],
       [2],
       [2],
       [1],
       [1],
       [2],
       [1],
       [3],
       [3],
       [2],
       [1],
       [3],
       [1],
       [3],
       [2],
       [3],
       [2],
       [3],
       [3],
       [3],
       [3],
       [1],
       [1],
       [3],
       [3],
       [3],
       [3],
       [3],
       [1],
       [2],
       [1],
       [3],
       [1],
       [3],
       [3],
       [3],
       [2],
       [3],
       [3],
       [2],
       [3],
       [3],
       [3],
       [1],
       [1],
       [3],
       [3],
       [1],
       [3],
       [2],
       [1],
       [1],
       [2],
       [2],
       [3],
       [1],
       [1],
       [2],
       [3],
       [3],
       [2],
       [3],
       [2],
       [3],
       [2],
       [3],
       [3],
       [1],
       [1],
       [1],
       [3],
       [1],
       [3],
       [3],
       [3],
       [1],
       [3],
       [3],
       [2],
       [1],
       [3],
       [1],
       [1],
       [3],
       [3],
       [3],
       [2],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [1],
       [3],
       [3],
       [3],
       [1],
       [3],
       [2],
       [2],
       [2],
       [3],
       [1],
       [1],
       [1],
       [3],
       [3],
       [1],
       [3],
       [3],
       [3],
       [2],
       [3],
       [3],
       [3],
       [3],
       [2],
       [3],
       [1],
       [1],
       [1],
       [1],
       [3],
       [1],
       [3],
       [3],
       [3],
       [3],
       [2],
       [3],
       [3],
       [3],
       [3],
       [1],
       [2],
       [1],
       [3],
       [2],
       [2],
       [1],
       [3],
       [3],
       [2],
       [2],
       [1],
       [1],
       [3],
       [2],
       [2],
       [3],
       [3],
       [3],
       [2],
       [2],
       [3],
       [2],
       [2],
       [3],
       [3],
       [3],
       [1],
       [3],
       [3],
       [1],
       [3],
       [2],
       [1],
       [2],
       [3],
       [3],
       [1],
       [2],
       [1],
       [2],
       [1],
       [3],
       [2],
       [3],
       [3],
       [1],
       [3],
       [3],
       [2],
       [2],
       [3],
       [3],
       [3],
       [2],
       [3],
       [3],
       [3],
       [1],
       [3],
       [1],
       [1],
       [3],
       [3],
       [3],
       [1],
       [3],
       [3],
       [3],
       [3],
       [3],
       [1],
       [3],
       [3],
       [3],
       [2],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [2],
       [1],
       [1],
       [1],
       [3],
       [3],
       [1],
       [3],
       [1],
       [2],
       [3],
       [3],
       [3],
       [2],
       [1],
       [3],
       [2],
       [2],
       [3],
       [2],
       [3],
       [2],
       [3],
       [1],
       [3],
       [1],
       [3],
       [1],
       [3],
       [3],
       [1],
       [3],
       [1],
       [3],
       [3],
       [3],
       [1],
       [3],
       [2],
       [1],
       [1],
       [2],
       [1],
       [3],
       [3],
       [2],
       [3],
       [2],
       [2],
       [1],
       [3],
       [1],
       [3],
       [3],
       [3],
       [2],
       [3],
       [1],
       [3],
       [2],
       [3],
       [2],
       [1],
       [3],
       [2],
       [3],
       [1],
       [3],
       [3],
       [3],
       [3],
       [3],
       [1],
       [2],
       [1],
       [3],
       [3],
       [3],
       [3],
       [3],
       [1],
       [1],
       [3],
       [1],
       [2],
       [2],
       [2],
       [3],
       [3],
       [1],
       [3],
       [3],
       [3],
       [3],
       [2],
       [3],
       [1],
       [2],
       [1],
       [2],
       [3],
       [3],
       [3],
       [2],
       [2],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [1],
       [3],
       [3],
       [1],
       [3],
       [2],
       [2],
       [3],
       [1],
       [2],
       [3],
       [3],
       [3],
       [1],
       [3],
       [3],
       [2],
       [1],
       [2],
       [1],
       [3],
       [1],
       [1],
       [3],
       [2],
       [3],
       [3],
       [3],
       [1],
       [3],
       [1],
       [2],
       [3],
       [3],
       [3],
       [1],
       [2],
       [3],
       [2],
       [1],
       [3],
       [3],
       [3],
       [2],
       [3],
       [3],
       [3],
       [3],
       [1],
       [1],
       [3],
       [3],
       [2],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [1],
       [3],
       [1],
       [3],
       [3],
       [1],
       [1],
       [1],
       [3],
       [3],
       [3],
       [3],
       [3],
       [1],
       [2],
       [2],
       [3],
       [1],
       [2],
       [3],
       [3],
       [1],
       [2],
       [3],
       [3],
       [3],
       [1],
       [3],
       [3],
       [1],
       [3],
       [2],
       [2],
       [1],
       [2],
       [3],
       [1],
       [3],
       [3],
       [3],
       [1],
       [2],
       [3],
       [1],
       [2],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [1],
       [1],
       [1],
       [3],
       [3],
       [3],
       [1],
       [1],
       [2],
       [3],
       [3],
       [1],
       [2],
       [2],
       [3],
       [2],
       [1],
       [2],
       [3],
       [2],
       [2],
       [2],
       [3],
       [2],
       [1],
       [3],
       [3],
       [1],
       [3],
       [1],
       [1],
       [1],
       [1],
       [3],
       [3],
       [3],
       [3],
       [2],
       [2],
       [1],
       [1],
       [3],
       [3],
       [3],
       [2],
       [3],
       [3],
       [1],
       [1],
       [3],
       [1],
       [3],
       [2],
       [3],
       [1],
       [3],
       [3],
       [3],
       [1],
       [3],
       [2],
       [3],
       [3],
       [2],
       [1],
       [3],
       [3],
       [2],
       [3],
       [3],
       [1],
       [1],
       [3],
       [1],
       [3],
       [3],
       [1],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [1],
       [3],
       [3],
       [1],
       [2],
       [3],
       [3],
       [1],
       [3],
       [2],
       [3],
       [3],
       [3],
       [1],
       [3],
       [2],
       [2],
       [1],
       [3],
       [3],
       [2],
       [2],
       [3],
       [3],
       [1],
       [3],
       [3],
       [1],
       [2],
       [3],
       [3],
       [3],
       [3],
       [3],
       [2],
       [3],
       [3],
       [2],
       [3],
       [1],
       [3],
       [1],
       [2],
       [1],
       [3],
       [2],
       [1],
       [2],
       [2],
       [3],
       [2],
       [2],
       [2],
       [1],
       [3],
       [2],
       [2],
       [2],
       [2],
       [3],
       [1],
       [1],
       [1],
       [3],
       [3],
       [3],
       [2]], dtype=int64)

In [28]:
from sklearn.preprocessing import OneHotEncoder

OHE_Embarked=OneHotEncoder(drop="first",sparse=False)
x_train_Embarked_ohe=OHE_Embarked.fit_transform(x_train_embarked)
x_test_Embarked_ohe=OHE_Embarked.fit_transform(x_test_embarked)

In [29]:
x_train_Embarked_ohe

array([[0., 1.],
       [0., 0.],
       [0., 1.],
       ...,
       [1., 0.],
       [0., 1.],
       [0., 1.]])

In [30]:
x_train_final=np.hstack((x_train["Pclass"].values.reshape(623,1),x_train_sex,x_train_age,x_train["Fare"].values.reshape(623,1),x_train_Embarked_ohe,x_train["family"].values.reshape(623,1)))

In [31]:
x_train_final[1]

array([ 1.    ,  0.    , 49.    , 76.7292,  0.    ,  0.    ,  1.    ])

In [32]:
x_test_final=np.hstack((x_test["Pclass"].values.reshape(268,1),x_test_sex,x_test_age,x_test["Fare"].values.reshape(268,1),x_test_Embarked_ohe,x_test["family"].values.reshape(268,1)))

In [33]:
x_test_final[1]

array([ 3.  ,  1.  , 18.  ,  7.55,  0.  ,  1.  ,  0.  ])

In [34]:
from sklearn.tree import DecisionTreeClassifier

In [35]:
clf=DecisionTreeClassifier()

In [36]:
clf.fit(x_train_final,y_train)

DecisionTreeClassifier()

In [37]:
y_pred=clf.predict(x_test_final)

In [38]:
from sklearn.metrics import accuracy_score

In [39]:
acc_sc=accuracy_score(y_test,y_pred)

In [40]:
print(acc_sc)

0.8022388059701493

In [42]:
clf.predict([[2,1,32,40,0,1,1]])

array([1], dtype=int64)

In [43]:
import pickle

In [44]:
pickle.dump(clf,open("titanic_model.pkl","wb"))
pickle.dump(OHE_sex,open("OHE_sex.pkl","wb"))
pickle.dump(OHE_Embarked,open("OHE_Embarked.pkl","wb"))