In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
df=pd.read_csv(r"C:\Users\heman\Downloads\train.csv")

In [3]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [4]:
df.drop(columns=["PassengerId","Name","Ticket","Cabin"],axis=1,inplace=True)

In [5]:
df

     Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0           0       3    male  22.0      1      0   7.2500        S
1           1       1  female  38.0      1      0  71.2833        C
2           1       3  female  26.0      0      0   7.9250        S
3           1       1  female  35.0      1      0  53.1000        S
4           0       3    male  35.0      0      0   8.0500        S
..        ...     ...     ...   ...    ...    ...      ...      ...
886         0       2    male  27.0      0      0  13.0000        S
887         1       1  female  19.0      0      0  30.0000        S
888         0       3  female   NaN      1      2  23.4500        S
889         1       1    male  26.0      0      0  30.0000        C
890         0       3    male  32.0      0      0   7.7500        Q

[891 rows x 8 columns]

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
x_train,x_test,y_train,y_test=train_test_split(df.drop(columns=["Survived"],axis=1),df["Survived"],test_size=0.2,random_state=42)

In [8]:
x_train.sample(5)

     Pclass     Sex   Age  SibSp  Parch      Fare Embarked
713       3    male  29.0      0      0    9.4833        S
718       3    male   NaN      0      0   15.5000        Q
182       3    male   9.0      4      2   31.3875        S
498       1  female  25.0      1      2  151.5500        S
423       3  female  28.0      1      1   14.4000        S

In [9]:
x_train.isnull().sum()

Pclass        0
Sex           0
Age         140
SibSp         0
Parch         0
Fare          0
Embarked      2
dtype: int64

In [10]:
x_train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 712 entries, 331 to 102
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Pclass    712 non-null    int64
 1   Sex       712 non-null    object
 2   Age       572 non-null    float64
 3   SibSp     712 non-null    int64
 4   Parch     712 non-null    int64
 5   Fare      712 non-null    float64
 6   Embarked  710 non-null    object
dtypes: float64(2), int64(3), object(2)
memory usage: 44.5+ KB

In [11]:
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler

In [12]:
numerical_features=["Age","Fare"]
numerical_tranforemer=Pipeline(steps=[("SI",SimpleImputer(strategy="median")),("SS",StandardScaler())])

categorical_feature=["Sex","Embarked"]
Categorical_transformer=Pipeline(steps=[("SIC",SimpleImputer(strategy="most_frequent")),("OHE",OneHotEncoder(handle_unknown="ignore"))])

In [13]:
from sklearn.compose import ColumnTransformer

In [14]:
trf=ColumnTransformer(transformers=[
    ("Num_trans",numerical_tranforemer,numerical_features),
    ("cat_trans",Categorical_transformer,categorical_feature)
])

In [15]:
from sklearn.linear_model import LogisticRegression

In [16]:
Clf=Pipeline(steps=[
    ("trf",trf),
    ("Model",LogisticRegression())
])

In [17]:
from sklearn import set_config
set_config(display="diagram")
Clf

Pipeline(steps=[('trf',
                 ColumnTransformer(transformers=[('Num_trans',
                                                  Pipeline(steps=[('SI',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('SS',
                                                                   StandardScaler())]),
                                                  ['Age', 'Fare']),
                                                 ('cat_trans',
                                                  Pipeline(steps=[('SIC',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('OHE',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['Sex', 'Embarked'])])),
                ('Model', LogisticRegression())])

In [18]:
from sklearn.model_selection import GridSearchCV

In [21]:
param_grid={"pre_num_imputer":["mean","median"],"pre_cat_imputer":["most_frequent","constant"],"classifier__C":[0.1,1,10,100]}
grid_search=GridSearchCV(Clf,param_grid,cv=10)

In [22]:
grid_search.fit(x_train,y_train)

ValueError: Invalid parameter classifier for estimator Pipeline(steps=[('trf',
                 ColumnTransformer(transformers=[('Num_trans',
                                                  Pipeline(steps=[('SI',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('SS',
                                                                   StandardScaler())]),
                                                  ['Age', 'Fare']),
                                                 ('cat_trans',
                                                  Pipeline(steps=[('SIC',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('OHE',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['Sex', 'Embarked'])])),
                ('Model', LogisticRegression())]). Check the list of available parameters with `estimator.get_params().keys()`.