In [1]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
df=pd.read_csv(r"C:\Users\heman\Downloads\train.csv",usecols=["Age","Pclass","Fare","Survived"])

In [3]:
df

     Survived  Pclass   Age     Fare
0           0       3  22.0   7.2500
1           1       1  38.0  71.2833
2           1       3  26.0   7.9250
3           1       1  35.0  53.1000
4           0       3  35.0   8.0500
..        ...     ...   ...      ...
886         0       2  27.0  13.0000
887         1       1  19.0  30.0000
888         0       3   NaN  23.4500
889         1       1  26.0  30.0000
890         0       3  32.0   7.7500

[891 rows x 4 columns]

In [4]:
df.isnull().mean()*100

Survived     0.00000
Pclass       0.00000
Age         19.86532
Fare         0.00000
dtype: float64

In [5]:
x=df[["Age","Fare","Pclass"]]
y=df["Survived"]

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [8]:
x_train

      Age      Fare  Pclass
331  45.5   28.5000       1
733  23.0   13.0000       2
382  32.0    7.9250       3
704  26.0    7.8542       3
813   6.0   31.2750       3
..    ...       ...     ...
106  21.0    7.6500       3
270   NaN   31.0000       1
860  41.0   14.1083       3
435  14.0  120.0000       1
102  21.0   77.2875       1

[712 rows x 3 columns]

In [9]:
from sklearn.impute import KNNImputer, SimpleImputer

In [10]:
knn=KNNImputer(n_neighbors=5,weights="distance")
x_train_transform=knn.fit_transform(x_train)
x_test_transform=knn.transform(x_test)

In [11]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [12]:
LG=LogisticRegression()
LG.fit(x_train_transform,y_train)
y_pred=LG.predict(x_test_transform)
print(accuracy_score(y_test,y_pred))

0.7374301675977654

In [13]:
# comparision with simple imputer

In [14]:
SI=SimpleImputer()
x_tarin_trf=SI.fit_transform(x_train)
x_test_trf=SI.transform(x_test)

In [15]:
LGS=LogisticRegression()
LGS.fit(x_tarin_trf,y_train)
y_pred1=LGS.predict(x_test_trf)
print(accuracy_score(y_test,y_pred1))

0.7374301675977654

In [16]:
df=df.dropna()

In [17]:
x_train,x_test,y_train,y_test=train_test_split(df.drop(columns=["Survived"],axis=1),df["Survived"],test_size=0.2,random_state=42)

In [18]:
LGN=LogisticRegression()
LGN.fit(x_train,y_train)
y_pred1=LGN.predict(x_test)
print(accuracy_score(y_test,y_pred1))

0.6713286713286714